name: Notion Calendar Auto Sync

on:
  schedule:
    - cron: "0 0 1 12 *"
  workflow_dispatch:

jobs:
  sync:
    name: Sync Notion Calendar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          US_EVENT_NOTION_DB_ID: ${{ secrets.US_EVENT_NOTION_DB_ID }}
          JP_EVENT_NOTION_DB_ID: ${{ secrets.JP_EVENT_NOTION_DB_ID }}
        run: npm run sync
